---
- name: add alacritty repository
  apt_repository:
    repo: ppa:mmstick76/alacritty
  become: yes

- name: install packages
  package:
    name: "{{ packages }}"
    state: present
  become: yes

- name: change default shell to zsh
  shell: "chsh -s /usr/bin/zsh {{ ansible_user }}"
  become: yes

- name: install du-dust
  shell: cargo install du-dust
  become: yes

- name: download z
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest: /usr/bin/z
    mode: 0777
  become: yes

- name: download antigen
  get_url:
    url: https://git.io/antigen
    dest: /usr/bin/antigen.zsh
    mode: 0777
  become: yes

- name: create .dotfiles directory
  file:
    name: ~/.dotfiles
    state: directory

- name: copy .dotfiles
  copy:
    src: "{{ item }}"
    dest: "~/.dotfiles/{{ item }}"
  loop:
    - include
    - .fzf.functions
    - aliases

- name: configure zsh
  copy:
    src: .zshrc
    dest: ~/.zshrc

- name: configure antigenrc
  copy:
    src: .antigenrc
    dest: ~/.antigenrc

- name: create alacritty config directory
  file:
    name: ~/.config/alacritty
    state: directory

- name: configure alacritty
  copy:
    src: alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml


