---
- name: install packages
  package:
    name: "{{ packages }}"
    state: present
  become: true

- name: copy requirements
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt

- name: install python modules
  pip:
    requirements: /tmp/requirements.txt
    state: present
    executable: pip3
  become: true
