---
- name: install packages
  package:
    name: "{{ packages }}"
    state: present
  become: true

- name: configure email
  shell: git config --global user.email "petrenyimisi@gmail.com"

- name: configure username
  shell: git config --global user.name "Mihaly Petrenyi"
