---
- name: download go
  get_url:
    url: https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
    dest: /tmp/go1.16.7.linux-amd64.tar.gz

- name: unarchive go
  unarchive:
    src: /tmp/go1.16.7.linux-amd64.tar.gz
    dest: /usr/local
  become: true

- name: add kind (go) to path
  lineinfile:
    dest: ~/.zshrc
    line: PATH="${PATH}:/usr/local/go/bin:/home/{{ ansible_user }}/go/bin"
