---
- name: download go
  get_url:
    url: https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
    dest: /tmp/go1.16.7.linux-amd64.tar.gz

- name: unarchive go
  unarchive:
    src: /tmp/go1.16.7.linux-amd64.tar.gz
    dest: /usr/local
  become: true
